# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron:  '30 23 1,15 * *' # 주기적으로 실행하기 위한 스케줄링 - cron 설정(매달 1,15일 23시 30분에 실행), 블로그에 글리젠이 안 될 경우 push 실패(수정해야함) 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install feedparser 
    - name: Run Update Python Script 
      run: | 
        python update_readme.py 
    - name: Update README.md file
      run: |
        git pull 
        git add . 
        git diff 
        git config --local user.email "sungmin69355@naver.com" 
        git config --local user.name "sungmin69355" 
        git commit -m "Update README.md" 
        git push
